name: Load CIFP Data

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

  workflow_dispatch:

jobs:
  load-cifp:
    name: Load CIFP Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Install dependencies
        run: pip3 install -r data/requirements.txt
      - name: Load CIFP data
        run: python3 data/load_cifp.py

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
