name: Load CIFP Data

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

  workflow_dispatch:

jobs:
  load-cifp:
    name: Load CIFP Data
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Install dependencies
        run: pip3 install -r data/requirements.txt
      - name: Test CIFP loader
        run: python3 -m pytest data/test_cifp.py -q
      - name: Load CIFP data
        run: python3 -u data/load_cifp.py
