name: Load Weather Forecasts

on:
  schedule:
    - cron: '45 * * * *' # Hourly at 45 minutes past the hour

  workflow_dispatch:

jobs:
  load-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Install dependencies
        run: pip3 install -r data/requirements.txt
      - name: Load weather data
        run: python3 data/load_weather.py
